- name: Установка зависимостей
  apt:
    name: ["iptables", "iproute2", "isc-dhcp-server (опционально)"]
    state: present
  tags: deps

- name: Настройка внутреннего интерфейса (LAN)
  template:
    src: "internal-iface.j2"
    dest: "/etc/net/ifaces/{{ internal_iface }}/options"
    owner: root
    group: root
    mode: 0644
  notify: restart network

- name: Включение IP-форвардинга
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    state: present
    reload: yes

- name: Настройка NAT
  iptables:
    table: nat
    chain: POSTROUTING
    out_interface: "{{ external_iface }}"
    jump: MASQUERADE
    comment: "SNAT для выхода в интернет"
  when: enable_nat

- name: Сохранение правил iptables
  copy:
    content: "{{ ansible_facts.iptables }}"
    dest: "/etc/iptables.rules"
  when: enable_nat

- name: Проверка подключения к интернету
  command: ping -c 3 8.8.8.8
  register: ping_result
  failed_when: ping_result.rc != 0
  tags: test