---
- name: Установка системных зависимостей (требует python3-apt)
  hosts: astra_linux
  become: yes
  gather_facts: false
  vars:
    ansible_python_interpreter: /usr/bin/python3  # Используем системный Python для apt-модулей
    qhb_repo_url: "https://repo.quantom.info/qhb/std-1/astra-smolensk/1.7/"
    gpg_key_url: "https://repo.quantom.info/qhb/keys/RPM-GPG-KEY-qhb"
  
  tasks:
    - name: Установка базовых пакетов
      raw: |
        apt-get update && 
        apt-get install -y gnupg2 apt-transport-https wget ca-certificates
      changed_when: false

    - name: Импорт GPG-ключа
      apt_key:
        url: "{{ gpg_key_url }}"
        state: present

    - name: Добавление репозитория QHB
      apt_repository:
        repo: "deb [arch=amd64] {{ qhb_repo_url }} stretch main"
        state: present
        filename: qhb.list

    - name: Установка основных пакетов QHB
      raw: apt-get install -y qhb-core qhb-contrib qcp qdl
      changed_when: false

- name: Настройка QHB (Python 3.9)
  hosts: astra_linux
  become: yes
  vars:
    ansible_python_interpreter: /usr/local/bin/python3.9  # Переключаемся на кастомный Python
    admin_user: "qhb_admin"
    admin_password: "!ChangeThisPassword123"
    test_db: "testdb"

  tasks:
    - name: Добавление PATH для QHB
      lineinfile:
        path: /etc/environment
        regexp: '^PATH='
        line: 'PATH="/usr/local/qhb/bin:$PATH"'
        state: present

    - name: Создание каталога данных
      file:
        path: /var/lib/qhb/data
        owner: qhb
        group: qhb
        state: directory
        mode: '0755'

    - name: Инициализация кластера
      command: /usr/local/qhb/bin/qhb_bootstrap -D /var/lib/qhb/data -U qhb
      become_user: qhb

    - name: Копирование основного конфига
      template:
        src: templates/qhb.conf.j2
        dest: /var/lib/qhb/data/qhb.conf
        owner: qhb
        group: qhb
        mode: '0644'
      notify: restart qhb

    - name: Настройка аутентификации
      blockinfile:
        path: /var/lib/qhb/data/qhb_hba.conf
        block: |
          # TYPE  DATABASE        USER            ADDRESS                 METHOD
          local   all             all                                     trust
          host    all             all             127.0.0.1/32            scram-sha-256
          host    all             all             ::1/128                 scram-sha-256
        owner: qhb
        group: qhb
      notify: restart qhb

    - name: Запуск службы QHB
      systemd:
        name: qhb
        state: started
        enabled: yes
        daemon_reload: yes

    - name: Проверка доступности
      wait_for:
        port: 5432
        delay: 10
        timeout: 60

    - name: Создание административной роли
      community.postgresql.postgresql_user:
        login_user: qhb
        login_host: localhost
        user: "{{ admin_user }}"
        password: "{{ admin_password }}"
        role_attr_flags: "SUPERUSER,CREATEDB,CREATEROLE,LOGIN"
        db: postgres

    - name: Создание тестовой БД
      community.postgresql.postgresql_db:
        name: "{{ test_db }}"
        owner: "{{ admin_user }}"
        login_user: "{{ admin_user }}"
        login_password: "{{ admin_password }}"
        login_host: localhost

  handlers:
    - name: restart qhb
      systemd:
        name: qhb
        state: restarted
