---
- name: Установка системных зависимостей
  hosts: astra_linux
  become: yes
  gather_facts: false
  vars:
    ansible_python_interpreter: /usr/bin/python3  # Используем системный Python для apt-модулей
    qhb_repo_url: "https://repo.quantom.info/qhb/std-1/astra-smolensk/1.7/"
    gpg_key_url: "https://repo.quantom.info/qhb/keys/RPM-GPG-KEY-qhb"
  
  tasks:
    - name: Установка Docker
      raw: |
        apt-get update && 
        apt-get install -y docker.io
      changed_when: false

   
