---
- name: Установка системных зависимостей
  hosts: astra_linux
  become: yes
  gather_facts: false
  vars:
    ansible_python_interpreter: /usr/bin/python3  # Используем системный Python для apt-модулей
  
  tasks:
    - name: Установка Docker и Git
      raw: |
        apt-get update && 
        sudo apt install docker.io docker-compose
      changed_when: false
      
    - name: Права для user docker
      raw: sudo usermod -aG docker $USER
      changed_when: false
      
    - name: Получение Dockerfile СУБД
      raw: |
        git clone https://github.com/lifecodev/devops-2025-course-project.git
      changed_when: false

    - name: Поднятие контейнера
      raw: cd devops-2025-course-project/docker-files && docker-compose build && docker-compose up -d
      changed_when: false
    
