version: "3.3"
services:
  qhb:
    build: qhb
    image: qhb
    ports:
      - "5432:5432"
    environment:
      - USER
    volumes:
      - ./qhb/pgdata:/qhb-data/
    networks:
      - frontend_network

networks:
  frontend_network:
    driver: bridge